name: NoëlFeed
favicon: null
layout_spectrum: 0.99619
typography_spectrum: 0.16906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4ecd5'
    - '#130c04'
    - '#423d2a'
    - '#938f76'
    - '#ebcd85'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
